/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lephuoctoan_2280603296;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.File;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author toan2
 */
public class GiaoDIen1 extends javax.swing.JFrame {
    private JTextField txtSourceFile;
    private JTextField txtDestFile;
    private JTextField txtChunkSize;
    private JTextArea txtLog;
    private JButton btnBrowse;
    private JButton btnProcess;
    private JButton btnClear;

    /**
     * Creates new form GiaoDIen1
     */
    public GiaoDIen1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setTitle("Cau 1: Xu Ly Tep Tin Nhi Phan");
        setSize(700, 500);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        // Main panel
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(10, 10));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        // Top panel - Input fields
        JPanel topPanel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.fill = GridBagConstraints.HORIZONTAL;
        
        // Source file
        gbc.gridx = 0; gbc.gridy = 0; gbc.weightx = 0;
        topPanel.add(new JLabel("File nguon:"), gbc);
        
        gbc.gridx = 1; gbc.weightx = 1;
        txtSourceFile = new JTextField(30);
        topPanel.add(txtSourceFile, gbc);
        
        gbc.gridx = 2; gbc.weightx = 0;
        btnBrowse = new JButton("Chon File");
        btnBrowse.addActionListener(e -> browseFile());
        topPanel.add(btnBrowse, gbc);
        
        // Destination file
        gbc.gridx = 0; gbc.gridy = 1; gbc.weightx = 0;
        topPanel.add(new JLabel("File dich:"), gbc);
        
        gbc.gridx = 1; gbc.weightx = 1; gbc.gridwidth = 2;
        txtDestFile = new JTextField("reconstructed.jpg");
        topPanel.add(txtDestFile, gbc);
        
        // Chunk size
        gbc.gridx = 0; gbc.gridy = 2; gbc.weightx = 0; gbc.gridwidth = 1;
        topPanel.add(new JLabel("Kich thuoc moi doan (byte):"), gbc);
        
        gbc.gridx = 1; gbc.weightx = 1; gbc.gridwidth = 2;
        txtChunkSize = new JTextField("100");
        topPanel.add(txtChunkSize, gbc);
        
        mainPanel.add(topPanel, BorderLayout.NORTH);
        
        // Center panel - Log area
        JPanel centerPanel = new JPanel(new BorderLayout());
        centerPanel.setBorder(BorderFactory.createTitledBorder("Ket qua xu ly"));
        
        txtLog = new JTextArea();
        txtLog.setEditable(false);
        txtLog.setFont(new Font("Monospaced", Font.PLAIN, 12));
        JScrollPane scrollPane = new JScrollPane(txtLog);
        centerPanel.add(scrollPane, BorderLayout.CENTER);
        
        mainPanel.add(centerPanel, BorderLayout.CENTER);
        
        // Bottom panel - Buttons
        JPanel bottomPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 10));
        
        btnProcess = new JButton("Xu Ly File");
        btnProcess.addActionListener(e -> processFile());
        bottomPanel.add(btnProcess);
        
        btnClear = new JButton("Xoa Log");
        btnClear.addActionListener(e -> txtLog.setText(""));
        bottomPanel.add(btnClear);
        
        mainPanel.add(bottomPanel, BorderLayout.SOUTH);
        
        add(mainPanel);
    }// </editor-fold>//GEN-END:initComponents
    
    private void browseFile() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chon file JPG hoac PDF");
        
        // Filter for JPG and PDF files
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "JPG & PDF files", "jpg", "jpeg", "pdf");
        fileChooser.setFileFilter(filter);
        
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            txtSourceFile.setText(selectedFile.getAbsolutePath());
            
            // Auto-set destination file name
            String fileName = selectedFile.getName();
            String extension = fileName.substring(fileName.lastIndexOf("."));
            txtDestFile.setText("reconstructed" + extension);
        }
    }
    
    private void processFile() {
        String sourceFile = txtSourceFile.getText().trim();
        String destFile = txtDestFile.getText().trim();
        String chunkSizeStr = txtChunkSize.getText().trim();
        
        if (sourceFile.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Vui long chon file nguon!", 
                "Thong bao", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (destFile.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Vui long nhap ten file dich!", 
                "Thong bao", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int chunkSize = Integer.parseInt(chunkSizeStr);
            if (chunkSize <= 0) {
                throw new NumberFormatException();
            }
            
            txtLog.setText("Dang xu ly...\n");
            
            // Run in background thread
            new Thread(() -> {
                String result = Cau1.splitAndMergeFile(sourceFile, destFile, chunkSize);
                SwingUtilities.invokeLater(() -> {
                    txtLog.append(result);
                    JOptionPane.showMessageDialog(this, 
                        "Hoan thanh!", 
                        "Thong bao", 
                        JOptionPane.INFORMATION_MESSAGE);
                });
            }).start();
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, 
                "Kich thuoc phai la so nguyen duong!", 
                "Loi", 
                JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDIen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDIen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDIen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDIen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDIen1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

