/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lephuoctoan_2280603296;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.ArrayList;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author toan2
 */
public class GiaoDIen1 extends javax.swing.JFrame {
    private JTextField txtSourceFile;
    private JTextField txtDestFile;
    private JTextField txtChunkSize;
    private JTextArea txtLog;
    private JButton btnBrowse;
    private JButton btnProcess;
    private JButton btnClear;

    /**
     * Creates new form GiaoDIen1
     */
    public GiaoDIen1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChonFile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCount = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnChonFile.setText("Chon FIle");
        btnChonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonFileActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Số file đã tách:");

        txtCount.setEditable(false);

        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtPath)
                        .addGap(18, 18, 18)
                        .addComponent(btnChonFile))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCount, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChonFile)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonFileActionPerformed
     JFileChooser fc = new JFileChooser();
    fc.setDialogTitle("Chọn file ảnh để tách và ghép");
    fc.setFileFilter(new FileNameExtensionFilter("Hình ảnh (JPG, PNG)", "jpg", "png", "jpeg"));

    int result = fc.showOpenDialog(this);
    if (result != JFileChooser.APPROVE_OPTION) return;

    File sourceFile = fc.getSelectedFile();
    txtPath.setText(sourceFile.getAbsolutePath());
    new Thread(() -> {
        try {
            java.util.List<String> partFiles = new ArrayList<>();
            int chunkSize = 100;
            byte[] buffer = new byte[chunkSize];

            try (FileInputStream fis = new FileInputStream(sourceFile)) {
                int bytesRead;
                int partCounter = 1;
                while ((bytesRead = fis.read(buffer)) > 0) {
                    String partName = "part_" + partCounter + ".dat";
                    try (FileOutputStream fos = new FileOutputStream(partName)) {
                        fos.write(buffer, 0, bytesRead);
                    }
                    partFiles.add(partName);
                    partCounter++;
                }
            }
            int totalParts = partFiles.size();
            SwingUtilities.invokeLater(() -> {
                txtCount.setText(String.valueOf(totalParts));
            });

            String destName = "reconstructed_" + sourceFile.getName();
            
            try (FileOutputStream fos = new FileOutputStream(destName)) {
                for (String part : partFiles) {
                    try (FileInputStream fis = new FileInputStream(part)) {
                        int bytesRead;
                        while ((bytesRead = fis.read(buffer)) > 0) {
                            fos.write(buffer, 0, bytesRead);
                        }
                    }
                }
            }

           
            File resultFile = new File(destName);
            if (resultFile.exists()) {
       
                ImageIcon icon = new ImageIcon(resultFile.getAbsolutePath());
                
               
                Image img = icon.getImage();
                Image scaledImg = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon scaledIcon = new ImageIcon(scaledImg);

               
                SwingUtilities.invokeLater(() -> {
                    lblImage.setIcon(scaledIcon);
                    JOptionPane.showMessageDialog(this, "Đã xử lý xong! Ảnh đã được khôi phục.");
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
            SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage()));
        }
    }).start();
    }//GEN-LAST:event_btnChonFileActionPerformed
    
    private void browseFile() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chon file JPG hoac PDF");
        
      
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "JPG & PDF files", "jpg", "jpeg", "pdf");
        fileChooser.setFileFilter(filter);
        
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            txtSourceFile.setText(selectedFile.getAbsolutePath());
            
         
            String fileName = selectedFile.getName();
            String extension = fileName.substring(fileName.lastIndexOf("."));
            txtDestFile.setText("reconstructed" + extension);
        }
    }
    
    private void processFile() {
        String sourceFile = txtSourceFile.getText().trim();
        String destFile = txtDestFile.getText().trim();
        String chunkSizeStr = txtChunkSize.getText().trim();
        
        if (sourceFile.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Vui long chon file nguon!", 
                "Thong bao", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (destFile.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Vui long nhap ten file dich!", 
                "Thong bao", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int chunkSize = Integer.parseInt(chunkSizeStr);
            if (chunkSize <= 0) {
                throw new NumberFormatException();
            }
            
            txtLog.setText("Dang xu ly...\n");
            
            // Run in background thread
            new Thread(() -> {
                String result = Cau1.splitAndMergeFile(sourceFile, destFile, chunkSize);
                SwingUtilities.invokeLater(() -> {
                    txtLog.append(result);
                    JOptionPane.showMessageDialog(this, 
                        "Hoan thanh!", 
                        "Thong bao", 
                        JOptionPane.INFORMATION_MESSAGE);
                });
            }).start();
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, 
                "Kich thuoc phai la so nguyen duong!", 
                "Loi", 
                JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDIen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDIen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDIen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDIen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDIen1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextField txtCount;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}

