/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lephuoctoan_2280603296;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author toan2
 */
public class GiaoDien2 extends javax.swing.JFrame {
    private JTextField txtId;
    private JTextField txtName;
    private JTextField txtSalary;
    private JButton btnAdd;
    private JButton btnSave;
    private JButton btnClear;
    private JTable table;
    private DefaultTableModel tableModel;
    private JTextArea txtLog;
    private List<Cau2.Employee> employees;

    /**
     * Creates new form GiaoDien2
     */
    public GiaoDien2() {
        employees = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setTitle("Cau 2: Quan Ly Nhan Vien - Xuat CSV");
        setSize(800, 600);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        JPanel mainPanel = new JPanel(new BorderLayout(10, 10));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        // Top panel - Input form
        JPanel topPanel = new JPanel(new GridBagLayout());
        topPanel.setBorder(BorderFactory.createTitledBorder("Nhap thong tin nhan vien"));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.fill = GridBagConstraints.HORIZONTAL;
        
        gbc.gridx = 0; gbc.gridy = 0; gbc.weightx = 0;
        topPanel.add(new JLabel("ID:"), gbc);
        gbc.gridx = 1; gbc.weightx = 1;
        txtId = new JTextField(20);
        topPanel.add(txtId, gbc);
        
        gbc.gridx = 0; gbc.gridy = 1; gbc.weightx = 0;
        topPanel.add(new JLabel("Ho Ten:"), gbc);
        gbc.gridx = 1; gbc.weightx = 1;
        txtName = new JTextField(20);
        topPanel.add(txtName, gbc);
        
        gbc.gridx = 0; gbc.gridy = 2; gbc.weightx = 0;
        topPanel.add(new JLabel("Luong:"), gbc);
        gbc.gridx = 1; gbc.weightx = 1;
        txtSalary = new JTextField(20);
        topPanel.add(txtSalary, gbc);
        
        gbc.gridx = 0; gbc.gridy = 3; gbc.gridwidth = 2;
        JPanel btnPanel = new JPanel(new FlowLayout());
        btnAdd = new JButton("Them Nhan Vien");
        btnAdd.addActionListener(e -> addEmployee());
        btnPanel.add(btnAdd);
        btnClear = new JButton("Xoa Danh Sach");
        btnClear.addActionListener(e -> clearTable());
        btnPanel.add(btnClear);
        topPanel.add(btnPanel, gbc);
        mainPanel.add(topPanel, BorderLayout.NORTH);
        
        // Center panel - Table
        JPanel centerPanel = new JPanel(new BorderLayout());
        centerPanel.setBorder(BorderFactory.createTitledBorder("Danh sach nhan vien"));
        String[] columns = {"ID", "Ho Ten", "Luong"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };
        table = new JTable(tableModel);
        centerPanel.add(new JScrollPane(table), BorderLayout.CENTER);
        mainPanel.add(centerPanel, BorderLayout.CENTER);
        
        // Bottom panel
        JPanel bottomPanel = new JPanel(new BorderLayout(5, 5));
        txtLog = new JTextArea(4, 50);
        txtLog.setEditable(false);
        txtLog.setFont(new Font("Monospaced", Font.PLAIN, 11));
        JScrollPane logScroll = new JScrollPane(txtLog);
        logScroll.setBorder(BorderFactory.createTitledBorder("Ket qua"));
        bottomPanel.add(logScroll, BorderLayout.CENTER);
        JPanel savePanel = new JPanel();
        btnSave = new JButton("Luu File CSV");
        btnSave.addActionListener(e -> saveToCSV());
        savePanel.add(btnSave);
        bottomPanel.add(savePanel, BorderLayout.SOUTH);
        mainPanel.add(bottomPanel, BorderLayout.SOUTH);
        add(mainPanel);
    }// </editor-fold>//GEN-END:initComponents
    
    private void addEmployee() {
        String id = txtId.getText().trim();
        String name = txtName.getText().trim();
        String salaryStr = txtSalary.getText().trim();
        if (id.isEmpty() || name.isEmpty() || salaryStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui long nhap day du thong tin!", "Canh bao", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            double salary = Double.parseDouble(salaryStr);
            Cau2.Employee emp = new Cau2.Employee(id, name, salary);
            employees.add(emp);
            tableModel.addRow(new Object[]{id, name, String.format("%.2f", salary)});
            txtId.setText(""); txtName.setText(""); txtSalary.setText("");
            txtId.requestFocus();
            txtLog.append("Da them: " + id + " - " + name + "\n");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Luong phai la so!", "Loi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void clearTable() {
        if (JOptionPane.showConfirmDialog(this, "Ban co chac muon xoa toan bo?", "Xac nhan", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            tableModel.setRowCount(0); employees.clear(); txtLog.append("Da xoa danh sach\n");
        }
    }
    
    private void saveToCSV() {
        if (employees.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Khong co nhan vien de luu!", "Canh bao", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String result = Cau2.saveEmployeesToCSV(employees, "employee.csv");
        txtLog.append(result);
        JOptionPane.showMessageDialog(this, "Da luu file employee.csv thanh cong!", "Thanh cong", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDien2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDien2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDien2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDien2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDien2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
